dAppLog( dLevel, "[CreateTime        ] : [%u]",Data->uiCreateTime);
dAppLog( dLevel, "[CreateMTime       ] : [%u]",Data->uiCreateMTime);
dAppLog( dLevel, "[SessStartTime     ] : [%u]",Data->uiSessStartTime);
dAppLog( dLevel, "[SessStartMTime    ] : [%u]",Data->uiSessStartMTime);
dAppLog( dLevel, "[SessEndTime       ] : [%u]",Data->uiSessEndTime);
dAppLog( dLevel, "[SessEndMTime      ] : [%u]",Data->uiSessEndMTime);
dAppLog( dLevel, "[SessDuration      ] : [%u]",Data->uiSessDuration      );
dAppLog( dLevel, "[WinCallID         ] : [%u]",Data->uiWinCallID         );
dAppLog( dLevel, "[ProtocolType      ] : [%d]",Data->usProtocolType      );
dAppLog( dLevel, "[MsgType           ] : [%d]",Data->usMsgType           );
dAppLog( dLevel, "[RetCode           ] : [%d]",Data->usRetCode           );
dAppLog( dLevel, "[NSAPI             ] : [%d]",Data->usNSAPI             );
dAppLog( dLevel, "[LinkedNSAPI       ] : [%d]",Data->usLinkedNSAPI       );
dAppLog( dLevel, "[SGSNRecovery      ] : [%d]",Data->usSGSNRecovery      );
dAppLog( dLevel, "[GGSNRecovery      ] : [%d]",Data->usGGSNRecovery      );
dAppLog( dLevel, "[TeardownInd       ] : [%d]",Data->usTeardownInd       );
dAppLog( dLevel, "[RAI_MCC           ] : [%d]",Data->usRAI_MCC           );
dAppLog( dLevel, "[RAI_MNC           ] : [%d]",Data->usRAI_MNC           );
dAppLog( dLevel, "[RAI_LAC           ] : [%d]",Data->usRAI_LAC           );
dAppLog( dLevel, "[RAI_RAC           ] : [%d]",Data->usRAI_RAC           );
dAppLog( dLevel, "[SGSNAddrSign      ] : [%u]",Data->uiSGSNAddrSign      );
dAppLog( dLevel, "[SGSNAddrData      ] : [%u]",Data->uiSGSNAddrData      );
dAppLog( dLevel, "[REQEndUserAddr    ] : [%u]",Data->uiREQEndUserAddr    );
dAppLog( dLevel, "[REQProConfOpt_ID  ] : [%hu]",Data->usREQProConfOpt_ID  );
dAppLog( dLevel, "[REQProConfOpt_Code] : [%hu]",Data->usREQProConfOpt_Code);
dAppLog( dLevel, "[IMSI              ] : [%s]",Data->szIMSI              );
dAppLog( dLevel, "[APN               ] : [%s]",Data->szAPN               );
dAppLog( dLevel, "[MSISDN            ] : [%s]",Data->szMSISDN            );
dAppLog( dLevel, "[REQQOS            ] : [%s]",Data->szREQQOS            );
dAppLog( dLevel, "[RESQOS            ] : [%s]",Data->szRESQOS            );
dAppLog( dLevel, "[ChargingID        ] : [%u]",Data->uiChargingID        );
dAppLog( dLevel, "[GGSNAddrSign      ] : [%u]",Data->uiGGSNAddrSign      );
dAppLog( dLevel, "[GGSNAddrData      ] : [%u]",Data->uiGGSNAddrData      );
dAppLog( dLevel, "[RESProConfOpt_ID  ] : [%hu]",Data->usRESProConfOpt_ID  );
dAppLog( dLevel, "[RESProConfOpt_Code] : [%hu]",Data->usRESProConfOpt_Code);
dAppLog( dLevel, "[RESEndUserAddr    ] : [%u]",Data->uiRESEndUserAddr    );
dAppLog( dLevel, "[ChargingChar      ] : [%hu]",Data->usChargingChar      );
dAppLog( dLevel, "[WSType            ] : [%hu]",Data->usWSType            );
dAppLog( dLevel, "[SelectionMode     ] : [%d]",Data->usSelectionMode     );
dAppLog( dLevel, "[Reordering        ] : [%d]",Data->usReordering        );
dAppLog( dLevel, "[SACInfo           ] : [%hu]",Data->usSACInfo           );
dAppLog( dLevel, "[SecNum            ] : [%d]",Data->usSecNum        );
dAppLog( dLevel, "[NodeBNum          ] : [%d]",Data->usNodeBNum      );
dAppLog( dLevel, "[RNCNum            ] : [%d]",Data->usRNCNum        );
dAppLog( dLevel, "[SvcArea           ] : [%d]",Data->usSvcArea       );
dAppLog( dLevel, "[Direction         ] : [%d]",Data->usDirection     );
dAppLog( dLevel, "[LOC_MCC           ] : [%d]",Data->usLOC_MCC);
dAppLog( dLevel, "[LOC_MNC           ] : [%d]",Data->usLOC_MNC);
dAppLog( dLevel, "[GNGRXFLAG            ] : [%d]",Data->usGnGrxFlag);
