CC			= gcc
RM			= rm -f
DEPEND		= makedepend
LINT		= lint
C64FLAGS	= 

INC_PATH	= -I. -I../../include 

LIB_PATH	= -L/usr/local/lib

CFLAGS		= -g -Wall -I$(INC_PATH) #-DDEBUG1 #-DMMDB_DEBUG #-Wall -D_REENTRANT #-DALONE_TEST

LIBS 		= -lsocket -lnsl

MAKEFILE    = Makefile

SRCS		=	test_p3db.c \

OBJS		= $(SRCS:.c=.o)

AOUT		= P3DB

DEST		= .

all:: $(AOUT) install

#$(OBJS): $(@:.o=.c)
#	$(CC) $(C64FLAGS) $(CFLAG) $(INC_PATH) -c $(@:.o=.c)

$(AOUT): $(OBJS)
	$(CC) -o $(AOUT) $(C64FLAGS) $(OBJS) $(LIB_PATH) $(LIBS) $(LDFLAGS)

shmmb_print:
	$(CC) -c  $(CFLAG)  $(INC_PATH) shmmb_print.c
	$(CC) -o shmmb_print shmmb_print.o $(OBJS) $(LIB_PATH) $(LIBS)

depend: $(SRCS)
	$(DEPEND) -o.o -f $(MAKEFILE) -- $(INC_PATH) --$(LIB_PATH) -- $(SRCS)

install:

clean:
	\rm -f $(OBJS) $(AOUT) core
