#ifndef __STATDEF_H__
#define __STATDEF_H__

#define STATRAD_ACCESS				1
#define STATRAD_ACCOUNTING			2

#define STATACCESS_TOT_AUTH_REQ				1
#define STATACCESS_TOT_AUTH_RES				2
#define STATACCESS_TOT_AUTH_TIMEOUT			3
#define STATACCESS_TOT_AUTH_ACPT			4
#define STATACCESS_TOT_AUTH_RJT				5
#define STATACCESS_NO_INTERIM_AUTH_ACPT		6
#define STATACCESS_TOT_CMPL_AUTH_TXN		7
#define STATACCESS_ONLY_AUTH_ACPT			8
#define STATACCESS_ONLY_AUTH_RJT			9
#define STATACCESS_DEC_ERR_AUTH_REQ			10
#define STATACCESS_DEC_ERR_AUTH_RES			11
#define STATACCESS_DUP_AUTH_REQ				12
#define STATACCESS_ETC_ERR_AUTH_REQ			13
#define STATACCESS_ETC_ERR_AUTH_RES			14

#define STATACCT_TOT_ACCT_REQ				1
#define STATACCT_TOT_ACCT_RES				2
#define STATACCT_TOT_ACCT_TIMEOUT			3
#define STATACCT_TOT_START					4
#define STATACCT_TOT_INTERIM				5
#define STATACCT_TOT_STOP					6
#define STATACCT_SESS_CONTINUE				7
#define STATACCT_NO_MDN_ACCT_RES			8
#define STATACCT_TOT_CMPL_ACCT_TXN			9
#define STATACCT_ONLY_ACCT_REQ				10
#define STATACCT_ONLY_ACCT_RES				11
#define STATACCT_DEC_ERR_ACCT_REQ			12
#define STATACCT_DEC_ERR_ACCT_RES			13
#define STATACCT_DUP_ACCT_REQ				14
#define STATACCT_ETC_ERR_ACCT_REQ			15
#define STATACCT_ETC_ERR_ACCT_RES			16

#endif /* __STATDEF_H__ */

