#ifndef _TCP_MSGQ_H_
#define _TCP_MSGQ_H_

#include "Analyze_Ext_Abs.h"

extern S32 dSend_TCP_Data(stMEMSINFO *pMEMSINFO, S32 dSeqProcID, U8 *pData);
extern S32 dSessUpdataMsg(stMEMSINFO *pMEMSINFO, TCP_SESS_KEY *pTCPSESSKEY, TCP_SESS *pTCPSESS);
extern S32 dTCPStartMsg(stMEMSINFO *pMEMSINFO, TCP_SESS_KEY *pTCPSESSKEY, TCP_SESS *pTCPSESS, INFO_ETH *pINFOETH);
extern S32 dSendPayLoad(stMEMSINFO *pMEMSINFO, TCP_SESS_KEY *pTCPSESSKEY, TCP_SESS *pTCPSESS);
extern S32 dSendAllData(stMEMSINFO *pMEMSINFO, TCP_SESS_KEY *pTCPSESSKEY, TCP_SESS *pTCPSESS);
extern S32 dTCPStopMsg(stMEMSINFO *pMEMSINFO, TCP_SESS_KEY *pTCPSESSKEY, TCP_SESS *pTCPSESS);


#endif /* _TCP_MSGQ_H_ */
