#ifndef _IHTTP_FUNC_H_
#define _IHTTP_FUNC_H_


/**
 * Declare functions
 */
extern S32 dProcHttpTrans(stMEMSINFO *pMEMSINFO, stHASHOINFO *pTCPHASH, stHASHOINFO *pHTTPHASH, TCP_INFO *pTCPINFO, U8 *pNode, U8 *pDATA);
extern S32 dCloseHttpTrans(stMEMSINFO *pMEMSINFO, stHASHOINFO *pHTTPHASH, HTTP_TSESS *pHTTPTSESS, HTTP_TRANS_KEY *pHTTPTRANSKEY, HTTP_TRANS *pHTTPTRANS);
extern S32 dCloseAllHttpTrans(stMEMSINFO *pMEMSINFO, stHASHOINFO *pHTTPHASH, HTTP_TSESS_KEY *pHTTPTSESSKEY, HTTP_TSESS *pHTTPTSESS, U16 usFailCode);
extern HTTP_TSESS *pCreateTcpSess(stMEMSINFO *pMEMSINFO, stHASHOINFO *pTCPHASH, stHASHOINFO *pHTTPHASH, HTTP_TSESS_KEY *pHTTPTSESSKEY, TCP_INFO *pTCPINFO);
extern S32 dCloseTcpSess(stMEMSINFO *pMEMSINFO, stHASHOINFO *pTCPHASH, stHASHOINFO *pHTTPHASH, HTTP_TSESS_KEY *pHTTPTSESSKEY, HTTP_TSESS *pHTTPTSESS);
extern S32 dProcStatus(stMEMSINFO *pMEMSINFO, stHASHOINFO *pHTTPHASH, HTTP_TSESS_KEY *pHTTPTSESSKEY, HTTP_TSESS *pHTTPTSESS, S32 isNotREQ, U16 failCode);

#endif	/* _IHTTP_FUNC_H_ */
