echo ""
echo "반드시 다음과 같이 소스 구조가 구성되어야 함"
echo ""
echo " [PROJECT] --- INC"
echo "            +- TAF"
echo "            +- TAM"
echo "            +- OAM"
echo "            +- LIB --> ['LIB' Project]"
echo ""
echo "다음의 명령어를 수행하거나, 별도의 위치에 LIB, Project를 위치시키고"
echo "sympolic link 를 위의 구조로 연결한다."
echo ""
echo "	$>cvs co -d LIB UPST_LIB"
echo "	$>cvs co OAM"
echo ""
echo "Good luck."
echo ""
