/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.2 2004/02/09 18:21:47 rstory Exp $
 *
 * $Id: chnTable.h,v 1.1 2011/08/31 11:24:18 hhbaek Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef CHNTABLE_H
#define CHNTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index chnIndex is internal */

    typedef struct chnTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER32 = ASN_INTEGER */
        long            chnIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   chnSystem[65535];
        long            chnSystem_len;

        /** INTEGER32 = ASN_INTEGER */
        long            chnPort;

        /** INTEGER32 = ASN_INTEGER */
        long            chnStatus;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } chnTable_context;

/*************************************************************
 * function declarations
 */
    void            init_chnTable(void);
    void            initialize_table_chnTable(void);
    const chnTable_context *chnTable_get_by_idx(netsnmp_index *);
    const chnTable_context *chnTable_get_by_idx_rs(netsnmp_index *,
                                                   int row_status);
    int             chnTable_get_value(netsnmp_request_info *,
                                       netsnmp_index *,
                                       netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      chnTable_oid[];
    extern size_t   chnTable_oid_len;

#define chnTable_TABLE_OID 1,3,6,1,4,1,28795,2,5

/*************************************************************
 * column number definitions for table chnTable
 */
#define COLUMN_CHNINDEX 1
#define COLUMN_CHNSYSTEM 2
#define COLUMN_CHNPORT 3
#define COLUMN_CHNSTATUS 4
#define chnTable_COL_MIN 1
#define chnTable_COL_MAX 4

    /*
     * comment out the following line if you don't handle SET-REQUEST for chnTable 
     */
#define chnTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define chnTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define chnTable_IDX2

#ifdef chnTable_SET_HANDLING

    int             chnTable_extract_index(chnTable_context * ctx,
                                           netsnmp_index * hdr);

    void            chnTable_set_reserve1(netsnmp_request_group *);
    void            chnTable_set_reserve2(netsnmp_request_group *);
    void            chnTable_set_action(netsnmp_request_group *);
    void            chnTable_set_commit(netsnmp_request_group *);
    void            chnTable_set_free(netsnmp_request_group *);
    void            chnTable_set_undo(netsnmp_request_group *);

    chnTable_context *chnTable_duplicate_row(chnTable_context *);
    netsnmp_index  *chnTable_delete_row(chnTable_context *);

    int             chnTable_can_delete(chnTable_context * undo_ctx,
                                        chnTable_context * row_ctx,
                                        netsnmp_request_group * rg);


#ifdef chnTable_ROW_CREATION
    chnTable_context *chnTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef chnTable_IDX2
    chnTable_context *chnTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
};
#endif

#endif /** CHNTABLE_H */
