/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.2 2004/02/09 18:21:47 rstory Exp $
 *
 * $Id: cpuTable.h,v 1.1 2011/08/31 11:24:18 hhbaek Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef CPUTABLE_H
#define CPUTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index cpuIndex is internal */

    typedef struct cpuTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER32 = ASN_INTEGER */
        long            cpuIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   cpuSystem[65535];
        long            cpuSystem_len;

        /** INTEGER32 = ASN_INTEGER */
        long            cpuUsage;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } cpuTable_context;

/*************************************************************
 * function declarations
 */
    void            init_cpuTable(void);
    void            initialize_table_cpuTable(void);
    const cpuTable_context *cpuTable_get_by_idx(netsnmp_index *);
    const cpuTable_context *cpuTable_get_by_idx_rs(netsnmp_index *,
                                                   int row_status);
    int             cpuTable_get_value(netsnmp_request_info *,
                                       netsnmp_index *,
                                       netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      cpuTable_oid[];
    extern size_t   cpuTable_oid_len;

#define cpuTable_TABLE_OID 1,3,6,1,4,1,28795,2,11

/*************************************************************
 * column number definitions for table cpuTable
 */
#define COLUMN_CPUINDEX 1
#define COLUMN_CPUSYSTEM 2
#define COLUMN_CPUUSAGE 3
#define cpuTable_COL_MIN 1
#define cpuTable_COL_MAX 3

    /*
     * comment out the following line if you don't handle SET-REQUEST for cpuTable 
     */
#define cpuTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define cpuTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define cpuTable_IDX2

#ifdef cpuTable_SET_HANDLING

    int             cpuTable_extract_index(cpuTable_context * ctx,
                                           netsnmp_index * hdr);

    void            cpuTable_set_reserve1(netsnmp_request_group *);
    void            cpuTable_set_reserve2(netsnmp_request_group *);
    void            cpuTable_set_action(netsnmp_request_group *);
    void            cpuTable_set_commit(netsnmp_request_group *);
    void            cpuTable_set_free(netsnmp_request_group *);
    void            cpuTable_set_undo(netsnmp_request_group *);

    cpuTable_context *cpuTable_duplicate_row(cpuTable_context *);
    netsnmp_index  *cpuTable_delete_row(cpuTable_context *);

    int             cpuTable_can_delete(cpuTable_context * undo_ctx,
                                        cpuTable_context * row_ctx,
                                        netsnmp_request_group * rg);


#ifdef cpuTable_ROW_CREATION
    cpuTable_context *cpuTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef cpuTable_IDX2
    cpuTable_context *cpuTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
};
#endif

#endif /** CPUTABLE_H */
