/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.2 2004/02/09 18:21:47 rstory Exp $
 *
 * $Id: dskTable.h,v 1.1 2011/08/31 11:24:18 hhbaek Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef DSKTABLE_H
#define DSKTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index dskIndex is internal */

    typedef struct dskTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER32 = ASN_INTEGER */
        long            dskIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   dskSystem[65535];
        long            dskSystem_len;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   dskPath[65535];
        long            dskPath_len;

        /** INTEGER32 = ASN_INTEGER */
        long            dskTotal;

        /** INTEGER32 = ASN_INTEGER */
        long            dskAvail;

        /** INTEGER32 = ASN_INTEGER */
        long            dskUsed;

        /** INTEGER32 = ASN_INTEGER */
        long            dskUsage;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } dskTable_context;

/*************************************************************
 * function declarations
 */
    void            init_dskTable(void);
    void            initialize_table_dskTable(void);
    const dskTable_context *dskTable_get_by_idx(netsnmp_index *);
    const dskTable_context *dskTable_get_by_idx_rs(netsnmp_index *,
                                                   int row_status);
    int             dskTable_get_value(netsnmp_request_info *,
                                       netsnmp_index *,
                                       netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      dskTable_oid[];
    extern size_t   dskTable_oid_len;

#define dskTable_TABLE_OID 1,3,6,1,4,1,28795,2,2

/*************************************************************
 * column number definitions for table dskTable
 */
#define COLUMN_DSKINDEX 1
#define COLUMN_DSKSYSTEM 2
#define COLUMN_DSKPATH 3
#define COLUMN_DSKTOTAL 4
#define COLUMN_DSKAVAIL 5
#define COLUMN_DSKUSED 6
#define COLUMN_DSKUSAGE 7
#define dskTable_COL_MIN 1
#define dskTable_COL_MAX 7

    /*
     * comment out the following line if you don't handle SET-REQUEST for dskTable 
     */
#define dskTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define dskTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define dskTable_IDX2

#ifdef dskTable_SET_HANDLING

    int             dskTable_extract_index(dskTable_context * ctx,
                                           netsnmp_index * hdr);

    void            dskTable_set_reserve1(netsnmp_request_group *);
    void            dskTable_set_reserve2(netsnmp_request_group *);
    void            dskTable_set_action(netsnmp_request_group *);
    void            dskTable_set_commit(netsnmp_request_group *);
    void            dskTable_set_free(netsnmp_request_group *);
    void            dskTable_set_undo(netsnmp_request_group *);

    dskTable_context *dskTable_duplicate_row(dskTable_context *);
    netsnmp_index  *dskTable_delete_row(dskTable_context *);

    int             dskTable_can_delete(dskTable_context * undo_ctx,
                                        dskTable_context * row_ctx,
                                        netsnmp_request_group * rg);


#ifdef dskTable_ROW_CREATION
    dskTable_context *dskTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef dskTable_IDX2
    dskTable_context *dskTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
};
#endif

#endif /** DSKTABLE_H */
