/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.2 2004/02/09 18:21:47 rstory Exp $
 *
 * $Id: edTable.h,v 1.1 2011/08/31 11:24:18 hhbaek Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef EDTABLE_H
#define EDTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index edIndex is internal */

    typedef struct edTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER32 = ASN_INTEGER */
        long            edIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   edSystem[65535];
        long            edSystem_len;

        /** INTEGER32 = ASN_INTEGER */
        long            edPort;

        /** INTEGER32 = ASN_INTEGER */
        long            edStatus;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } edTable_context;

/*************************************************************
 * function declarations
 */
    void            init_edTable(void);
    void            initialize_table_edTable(void);
    const edTable_context *edTable_get_by_idx(netsnmp_index *);
    const edTable_context *edTable_get_by_idx_rs(netsnmp_index *,
                                                 int row_status);
    int             edTable_get_value(netsnmp_request_info *,
                                      netsnmp_index *,
                                      netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      edTable_oid[];
    extern size_t   edTable_oid_len;

#define edTable_TABLE_OID 1,3,6,1,4,1,28795,2,6

/*************************************************************
 * column number definitions for table edTable
 */
#define COLUMN_EDINDEX 1
#define COLUMN_EDSYSTEM 2
#define COLUMN_EDPORT 3
#define COLUMN_EDSTATUS 4
#define edTable_COL_MIN 1
#define edTable_COL_MAX 4

    /*
     * comment out the following line if you don't handle SET-REQUEST for edTable 
     */
#define edTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define edTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define edTable_IDX2

#ifdef edTable_SET_HANDLING

    int             edTable_extract_index(edTable_context * ctx,
                                          netsnmp_index * hdr);

    void            edTable_set_reserve1(netsnmp_request_group *);
    void            edTable_set_reserve2(netsnmp_request_group *);
    void            edTable_set_action(netsnmp_request_group *);
    void            edTable_set_commit(netsnmp_request_group *);
    void            edTable_set_free(netsnmp_request_group *);
    void            edTable_set_undo(netsnmp_request_group *);

    edTable_context *edTable_duplicate_row(edTable_context *);
    netsnmp_index  *edTable_delete_row(edTable_context *);

    int             edTable_can_delete(edTable_context * undo_ctx,
                                       edTable_context * row_ctx,
                                       netsnmp_request_group * rg);


#ifdef edTable_ROW_CREATION
    edTable_context *edTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef edTable_IDX2
    edTable_context *edTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
};
#endif

#endif /** EDTABLE_H */
