/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.2 2004/02/09 18:21:47 rstory Exp $
 *
 * $Id: fanTable.h,v 1.1 2011/08/31 11:24:19 hhbaek Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef FANTABLE_H
#define FANTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index fanIndex is internal */

    typedef struct fanTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER = ASN_INTEGER */
        long            fanIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   fanSystem[65535];
        long            fanSystem_len;

        /** INTEGER32 = ASN_INTEGER */
        long            fanId;

        /** INTEGER = ASN_INTEGER */
        long            fanStatus;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } fanTable_context;

/*************************************************************
 * function declarations
 */
    void            init_fanTable(void);
    void            initialize_table_fanTable(void);
    const fanTable_context *fanTable_get_by_idx(netsnmp_index *);
    const fanTable_context *fanTable_get_by_idx_rs(netsnmp_index *,
                                                   int row_status);
    int             fanTable_get_value(netsnmp_request_info *,
                                       netsnmp_index *,
                                       netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      fanTable_oid[];
    extern size_t   fanTable_oid_len;

#define fanTable_TABLE_OID 1,3,6,1,4,1,28795,2,9

/*************************************************************
 * column number definitions for table fanTable
 */
#define COLUMN_FANINDEX 1
#define COLUMN_FANSYSTEM 2
#define COLUMN_FANID 3
#define COLUMN_FANSTATUS 4
#define fanTable_COL_MIN 1
#define fanTable_COL_MAX 4

    /*
     * comment out the following line if you don't handle SET-REQUEST for fanTable 
     */
#define fanTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define fanTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define fanTable_IDX2

#ifdef fanTable_SET_HANDLING

    int             fanTable_extract_index(fanTable_context * ctx,
                                           netsnmp_index * hdr);

    void            fanTable_set_reserve1(netsnmp_request_group *);
    void            fanTable_set_reserve2(netsnmp_request_group *);
    void            fanTable_set_action(netsnmp_request_group *);
    void            fanTable_set_commit(netsnmp_request_group *);
    void            fanTable_set_free(netsnmp_request_group *);
    void            fanTable_set_undo(netsnmp_request_group *);

    fanTable_context *fanTable_duplicate_row(fanTable_context *);
    netsnmp_index  *fanTable_delete_row(fanTable_context *);

    int             fanTable_can_delete(fanTable_context * undo_ctx,
                                        fanTable_context * row_ctx,
                                        netsnmp_request_group * rg);


#ifdef fanTable_ROW_CREATION
    fanTable_context *fanTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef fanTable_IDX2
    fanTable_context *fanTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
};
#endif

#endif /** FANTABLE_H */
