/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.2 2004/02/09 18:21:47 rstory Exp $
 *
 * $Id: memTable.h,v 1.1 2011/08/31 11:24:19 hhbaek Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef MEMTABLE_H
#define MEMTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index memIndex is internal */

    typedef struct memTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER32 = ASN_INTEGER */
        long            memIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   memSystem[65535];
        long            memSystem_len;

        /** INTEGER32 = ASN_INTEGER */
        long            memTotal;

        /** INTEGER32 = ASN_INTEGER */
        long            memAvail;

        /** INTEGER32 = ASN_INTEGER */
        long            memUsed;

        /** INTEGER32 = ASN_INTEGER */
        long            memUsage;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } memTable_context;

/*************************************************************
 * function declarations
 */
    void            init_memTable(void);
    void            initialize_table_memTable(void);
    const memTable_context *memTable_get_by_idx(netsnmp_index *);
    const memTable_context *memTable_get_by_idx_rs(netsnmp_index *,
                                                   int row_status);
    int             memTable_get_value(netsnmp_request_info *,
                                       netsnmp_index *,
                                       netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      memTable_oid[];
    extern size_t   memTable_oid_len;

#define memTable_TABLE_OID 1,3,6,1,4,1,28795,2,4

/*************************************************************
 * column number definitions for table memTable
 */
#define COLUMN_MEMINDEX 1
#define COLUMN_MEMSYSTEM 2
#define COLUMN_MEMTOTAL 3
#define COLUMN_MEMAVAIL 4
#define COLUMN_MEMUSED 5
#define COLUMN_MEMUSAGE 6
#define memTable_COL_MIN 1
#define memTable_COL_MAX 6

    /*
     * comment out the following line if you don't handle SET-REQUEST for memTable 
     */
#define memTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define memTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define memTable_IDX2

#ifdef memTable_SET_HANDLING

    int             memTable_extract_index(memTable_context * ctx,
                                           netsnmp_index * hdr);

    void            memTable_set_reserve1(netsnmp_request_group *);
    void            memTable_set_reserve2(netsnmp_request_group *);
    void            memTable_set_action(netsnmp_request_group *);
    void            memTable_set_commit(netsnmp_request_group *);
    void            memTable_set_free(netsnmp_request_group *);
    void            memTable_set_undo(netsnmp_request_group *);

    memTable_context *memTable_duplicate_row(memTable_context *);
    netsnmp_index  *memTable_delete_row(memTable_context *);

    int             memTable_can_delete(memTable_context * undo_ctx,
                                        memTable_context * row_ctx,
                                        netsnmp_request_group * rg);


#ifdef memTable_ROW_CREATION
    memTable_context *memTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef memTable_IDX2
    memTable_context *memTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
};
#endif

#endif /** MEMTABLE_H */
