/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.2 2004/02/09 18:21:47 rstory Exp $
 *
 * $Id: ntpTable.h,v 1.1 2011/08/31 11:24:19 hhbaek Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef NTPTABLE_H
#define NTPTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index ntpIndex is internal */

    typedef struct ntpTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER32 = ASN_INTEGER */
        long            ntpIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   ntpSystem[65535];
        long            ntpSystem_len;

        /** INTEGER32 = ASN_INTEGER */
        long            ntpId;

        /** INTEGER32 = ASN_INTEGER */
        long            ntpStatus;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } ntpTable_context;

/*************************************************************
 * function declarations
 */
    void            init_ntpTable(void);
    void            initialize_table_ntpTable(void);
    const ntpTable_context *ntpTable_get_by_idx(netsnmp_index *);
    const ntpTable_context *ntpTable_get_by_idx_rs(netsnmp_index *,
                                                   int row_status);
    int             ntpTable_get_value(netsnmp_request_info *,
                                       netsnmp_index *,
                                       netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      ntpTable_oid[];
    extern size_t   ntpTable_oid_len;

#define ntpTable_TABLE_OID 1,3,6,1,4,1,28795,2,10

/*************************************************************
 * column number definitions for table ntpTable
 */
#define COLUMN_NTPINDEX 1
#define COLUMN_NTPSYSTEM 2
#define COLUMN_NTPID 3
#define COLUMN_NTPSTATUS 4
#define ntpTable_COL_MIN 1
#define ntpTable_COL_MAX 4

    /*
     * comment out the following line if you don't handle SET-REQUEST for ntpTable 
     */
#define ntpTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define ntpTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define ntpTable_IDX2

#ifdef ntpTable_SET_HANDLING

    int             ntpTable_extract_index(ntpTable_context * ctx,
                                           netsnmp_index * hdr);

    void            ntpTable_set_reserve1(netsnmp_request_group *);
    void            ntpTable_set_reserve2(netsnmp_request_group *);
    void            ntpTable_set_action(netsnmp_request_group *);
    void            ntpTable_set_commit(netsnmp_request_group *);
    void            ntpTable_set_free(netsnmp_request_group *);
    void            ntpTable_set_undo(netsnmp_request_group *);

    ntpTable_context *ntpTable_duplicate_row(ntpTable_context *);
    netsnmp_index  *ntpTable_delete_row(ntpTable_context *);

    int             ntpTable_can_delete(ntpTable_context * undo_ctx,
                                        ntpTable_context * row_ctx,
                                        netsnmp_request_group * rg);


#ifdef ntpTable_ROW_CREATION
    ntpTable_context *ntpTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef ntpTable_IDX2
    ntpTable_context *ntpTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
};
#endif

#endif /** NTPTABLE_H */
