/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.2 2004/02/09 18:21:47 rstory Exp $
 *
 * $Id: prTable.h,v 1.1 2011/08/31 11:24:19 hhbaek Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef PRTABLE_H
#define PRTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index prIndex is internal */

    typedef struct prTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER32 = ASN_INTEGER */
        long            prIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   prSystem[65535];
        long            prSystem_len;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   prName[65535];
        long            prName_len;

        /** INTEGER32 = ASN_INTEGER */
        long            prPid;

        /** OCTETSTR = ASN_OCTET_STR */
        time_t			prUptime;

        /** INTEGER32 = ASN_INTEGER */
        long            prStatus;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } prTable_context;

/*************************************************************
 * function declarations
 */
    void            init_prTable(void);
    void            initialize_table_prTable(void);
    const prTable_context *prTable_get_by_idx(netsnmp_index *);
    const prTable_context *prTable_get_by_idx_rs(netsnmp_index *,
                                                 int row_status);
    int             prTable_get_value(netsnmp_request_info *,
                                      netsnmp_index *,
                                      netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      prTable_oid[];
    extern size_t   prTable_oid_len;

#define prTable_TABLE_OID 1,3,6,1,4,1,28795,2,1

/*************************************************************
 * column number definitions for table prTable
 */
#define COLUMN_PRINDEX 1
#define COLUMN_PRSYSTEM 2
#define COLUMN_PRNAME 3
#define COLUMN_PRPID 4
#define COLUMN_PRUPTIME 5
#define COLUMN_PRSTATUS 6
#define prTable_COL_MIN 1
#define prTable_COL_MAX 6

    /*
     * comment out the following line if you don't handle SET-REQUEST for prTable
     */
#define prTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows
     */
#define prTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index
     */
#define prTable_IDX2

#ifdef prTable_SET_HANDLING

    int             prTable_extract_index(prTable_context * ctx,
                                          netsnmp_index * hdr);

    void            prTable_set_reserve1(netsnmp_request_group *);
    void            prTable_set_reserve2(netsnmp_request_group *);
    void            prTable_set_action(netsnmp_request_group *);
    void            prTable_set_commit(netsnmp_request_group *);
    void            prTable_set_free(netsnmp_request_group *);
    void            prTable_set_undo(netsnmp_request_group *);

    prTable_context *prTable_duplicate_row(prTable_context *);
    netsnmp_index  *prTable_delete_row(prTable_context *);

    int             prTable_can_delete(prTable_context * undo_ctx,
                                       prTable_context * row_ctx,
                                       netsnmp_request_group * rg);


#ifdef prTable_ROW_CREATION
    prTable_context *prTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef prTable_IDX2
    prTable_context *prTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
};
#endif

#endif /** PRTABLE_H */
