/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.2 2004/02/09 18:21:47 rstory Exp $
 *
 * $Id: pwrTable.h,v 1.1 2011/08/31 11:24:20 hhbaek Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef PWRTABLE_H
#define PWRTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index pwrIndex is internal */

    typedef struct pwrTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER32 = ASN_INTEGER */
        long            pwrIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   pwrSystem[65535];
        long            pwrSystem_len;

        /** INTEGER32 = ASN_INTEGER */
        long            pwrId;

        /** INTEGER32 = ASN_INTEGER */
        long            pwrStatus;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } pwrTable_context;

/*************************************************************
 * function declarations
 */
    void            init_pwrTable(void);
    void            initialize_table_pwrTable(void);
    const pwrTable_context *pwrTable_get_by_idx(netsnmp_index *);
    const pwrTable_context *pwrTable_get_by_idx_rs(netsnmp_index *,
                                                   int row_status);
    int             pwrTable_get_value(netsnmp_request_info *,
                                       netsnmp_index *,
                                       netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      pwrTable_oid[];
    extern size_t   pwrTable_oid_len;

#define pwrTable_TABLE_OID 1,3,6,1,4,1,28795,2,8

/*************************************************************
 * column number definitions for table pwrTable
 */
#define COLUMN_PWRINDEX 1
#define COLUMN_PWRSYSTEM 2
#define COLUMN_PWRID 3
#define COLUMN_PWRSTATUS 4
#define pwrTable_COL_MIN 1
#define pwrTable_COL_MAX 4

    /*
     * comment out the following line if you don't handle SET-REQUEST for pwrTable 
     */
#define pwrTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define pwrTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define pwrTable_IDX2

#ifdef pwrTable_SET_HANDLING

    int             pwrTable_extract_index(pwrTable_context * ctx,
                                           netsnmp_index * hdr);

    void            pwrTable_set_reserve1(netsnmp_request_group *);
    void            pwrTable_set_reserve2(netsnmp_request_group *);
    void            pwrTable_set_action(netsnmp_request_group *);
    void            pwrTable_set_commit(netsnmp_request_group *);
    void            pwrTable_set_free(netsnmp_request_group *);
    void            pwrTable_set_undo(netsnmp_request_group *);

    pwrTable_context *pwrTable_duplicate_row(pwrTable_context *);
    netsnmp_index  *pwrTable_delete_row(pwrTable_context *);

    int             pwrTable_can_delete(pwrTable_context * undo_ctx,
                                        pwrTable_context * row_ctx,
                                        netsnmp_request_group * rg);


#ifdef pwrTable_ROW_CREATION
    pwrTable_context *pwrTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef pwrTable_IDX2
    pwrTable_context *pwrTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
};
#endif

#endif /** PWRTABLE_H */
