/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.array-user.conf,v 5.18.2.2 2004/02/09 18:21:47 rstory Exp $
 *
 * $Id: queTable.h,v 1.1 2011/08/31 11:24:20 hhbaek Exp $
 *
 * Yes, there is lots of code here that you might not use. But it is much
 * easier to remove code than to add it!
 */
#ifndef QUETABLE_H
#define QUETABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include <net-snmp/net-snmp-config.h>
#include <net-snmp/library/container.h>
#include <net-snmp/agent/table_array.h>

        /** Index queIndex is internal */

    typedef struct queTable_context_s {
        netsnmp_index   index;
                         /** THIS MUST BE FIRST!!! */

    /*************************************************************
     * You can store data internally in this structure.
     *
     * TODO: You will probably have to fix a few types here...
     */
        /** INTEGER32 = ASN_INTEGER */
        long            queIndex;

        /** OCTETSTR = ASN_OCTET_STR */
        unsigned char   queSystem[65535];
        long            queSystem_len;

        /** INTEGER32 = ASN_INTEGER */
        long            queTotal;

        /** INTEGER32 = ASN_INTEGER */
        long            queAvail;

        /** INTEGER32 = ASN_INTEGER */
        long            queUsed;

        /** INTEGER32 = ASN_INTEGER */
        long            queUsage;


        /*
         * OR
         *
         * Keep a pointer to your data
         */
        void           *data;

        /*
         *add anything else you want here
         */

    } queTable_context;

/*************************************************************
 * function declarations
 */
    void            init_queTable(void);
    void            initialize_table_queTable(void);
    const queTable_context *queTable_get_by_idx(netsnmp_index *);
    const queTable_context *queTable_get_by_idx_rs(netsnmp_index *,
                                                   int row_status);
    int             queTable_get_value(netsnmp_request_info *,
                                       netsnmp_index *,
                                       netsnmp_table_request_info *);


/*************************************************************
 * oid declarations
 */
    extern oid      queTable_oid[];
    extern size_t   queTable_oid_len;

#define queTable_TABLE_OID 1,3,6,1,4,1,28795,2,7

/*************************************************************
 * column number definitions for table queTable
 */
#define COLUMN_QUEINDEX 1
#define COLUMN_QUESYSTEM 2
#define COLUMN_QUETOTAL 3
#define COLUMN_QUEAVAIL 4
#define COLUMN_QUEUSED 5
#define COLUMN_QUEUSAGE 6
#define queTable_COL_MIN 1
#define queTable_COL_MAX 6

    /*
     * comment out the following line if you don't handle SET-REQUEST for queTable 
     */
#define queTable_SET_HANDLING

    /*
     * comment out the following line if you can't create new rows 
     */
#define queTable_ROW_CREATION

    /*
     * comment out the following line if you don't want the secondary index 
     */
#define queTable_IDX2

#ifdef queTable_SET_HANDLING

    int             queTable_extract_index(queTable_context * ctx,
                                           netsnmp_index * hdr);

    void            queTable_set_reserve1(netsnmp_request_group *);
    void            queTable_set_reserve2(netsnmp_request_group *);
    void            queTable_set_action(netsnmp_request_group *);
    void            queTable_set_commit(netsnmp_request_group *);
    void            queTable_set_free(netsnmp_request_group *);
    void            queTable_set_undo(netsnmp_request_group *);

    queTable_context *queTable_duplicate_row(queTable_context *);
    netsnmp_index  *queTable_delete_row(queTable_context *);

    int             queTable_can_delete(queTable_context * undo_ctx,
                                        queTable_context * row_ctx,
                                        netsnmp_request_group * rg);


#ifdef queTable_ROW_CREATION
    queTable_context *queTable_create_row(netsnmp_index *);
#endif
#endif

#ifdef queTable_IDX2
    queTable_context *queTable_get(const char *name, int len);
#endif

#ifdef __cplusplus
};
#endif

#endif /** QUETABLE_H */
