/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf,v 5.2.2.1 2004/04/15 12:29:06 dts12 Exp $
 */
#ifndef UPRESTO_H
#define UPRESTO_H

/*
 * Function declarations
 */
int send_stop_trap(void);
int send_start_trap(void);

#endif	/* UPRESTO_H */
