MAKEFILE	= Makefile
TOP_LIB		= 
TOP_BIN		=
LIBRARY 	=
INCLUDES	=
DEFINES		= 
CFLAGS		=

TARGET		=
SRCS		=
OBJS		=
LIBS		= *.a
BINS		=

#-----------------------------------------------------------
#

all:

install:

clean:
	rm -f $(LIBS) core*

