ipcrm -Q 0x5302
ipcrm -Q 0x5303
ipcrm -Q 0x5313
ipcrm -Q 0x5306
ipcrm -Q 0x5305
ipcrm -Q 0x5304
ipcrm -Q 0x5312
ipcrm -Q 0x5309
ipcrm -Q 0x5301
ipcrm -Q 0x5300
ipcrm -Q 0x5307    
ipcrm -Q 0x5317
ipcrm -Q 0x5316
ipcrm -Q 0x5315
ipcrm -Q 0x5314

ipcrm -M 0x11111
ipcrm -M 0x11112
ipcrm -M 0x11113
ipcrm -M 0x11114                                                                                            
ipcrm -M 0x11117                                                                                            
                                                                                                   
ipcrm -M 0x5114                                                                                             
ipcrm -M 0x5115                                                                                             
ipcrm -M 0x5116                                                                                             
ipcrm -M 0x5117                                                                                             
ipcrm -M 0x5118                                                                                             
ipcrm -M 0x5119                                                                                             
ipcrm -M 0x5120                                                                                             
ipcrm -M 0x5121                                                                                             
ipcrm -M 0x5122                                                                                             
ipcrm -M 0x5123                                                                                             
ipcrm -M 0x5124                                                                                             
ipcrm -M 0x5125                                                                                             
ipcrm -M 0x5126                                                                                             
ipcrm -M 0x5127                                                                                             
ipcrm -M 0x5128                                                                                             
ipcrm -M 0x5129                                                                                             
ipcrm -M 0x5130                                                                                             
ipcrm -M 0x5131                                                                                             
ipcrm -M 0x5132                                                                                             
ipcrm -M 0x5133                                                                                             
ipcrm -M 0x5134                                                                                             
ipcrm -M 0x5135                                                                                             
ipcrm -M 0x5136                                                                                             
ipcrm -M 0x5137                                                                                             
ipcrm -M 0x5138                                                                                             
ipcrm -M 0x5139                                                                                             
ipcrm -M 0x5140                                                                                             
ipcrm -M 0x5141                                                                                             
                                                                                                   
ipcrm -M 0x2813                                                                                             
ipcrm -M 0x2820                                                                                             
ipcrm -M 0x282C                                                                                             
ipcrm -M 0x282D                                                                                             
ipcrm -M 0x3012            
