create table acct_info (
		rad_code 			INT,
		rad_id	 			INT,
		username_len		INT,
		nasport_id_len		INT,
		udr_sequence		INT,
		time_stamp			varchar(33),
		aaa_ip				varchar(16),
		udr_key				INT,
		framed_ip			varchar(16),
		nas_ip				varchar(16),
		pcf_ip				varchar(16),
		ha_ip				varchar(16),
		radius_len			INT,
		sess_continue		INT,
		begin_sess			INT,
		svc_opt				INT,
		acct_stat_type		INT,
		comp_tunneled		INT,
		num_act				INT,
		svc_type			INT,
		fwd_fch_mux			INT,
		rev_fch_mux			INT,
		fwd_traf_type		INT,
		rev_traf_type		INT,
		fch_size			INT,
		fwd_fchrc			INT,
		rev_fchrc			INT,
		ip_tech				INT,
		dcch_size			INT,
		nas_port			INT,
		nas_port_type		INT,
		release_ind			INT,
		acct_in_oct			INT,
		acct_out_oct		INT,
		acct_in_pkt			INT,
		acct_out_pkt		INT,
		event_time			varchar(33),
		acct_time			INT,
		acct_sess_time		INT,
		acct_delay_time		INT,
		term_sdb_oct_cnt	INT,
		org_sdb_oct_cnt		INT,
		term_num_sdb		INT,
		org_num_sdb			INT,
		rcv_hdlc_oct		INT,
		ip_qos				INT,
		air_qos				INT,
		rp_connect_id		INT,
		bad_ppp_frame_cnt	INT,
		acct_auth			INT,
		acct_term_cause		INT,
		always_on			INT,
		user_id				INT,
		in_mip_sig_cnt		INT,
		out_mip_sig_cnt		INT,
		acct_interim		INT,
		acct_sess_id		varchar(32)	NOT NULL,
		correl_id			varchar(32),
		retry_flag			INT,
		authen				varchar(33),
		mdn					varchar(17),
		esn					varchar(16),
		user_name			varchar(72),
		bsid				varchar(12),
		nas_port_id			varchar(24),
		min					varchar(17)	NOT NULL,
		crt_year			INT NOT NULL,
		crt_time			INT NOT NULL,
		matching_key		INT,
		key idx1 (crt_year),
		key idx2 (crt_time));

create table udr_info (
		acct_sess_id		varchar(32)	NOT NULL,
		min					varchar(17) NOT NULL,
		udr_index		INT,
		data_svc_type		INT,
		tran_id				INT,
		req_time			varchar(33),
		res_time			varchar(33),
		session_time		INT,
		dest_ip				varchar(16),
		dest_port			INT,
		src_port			INT,
		c_type				INT,
		app_id				varchar(12),
		content_code		varchar(14),
		method_type			INT,
		result_code			INT,
		ip_up_size			INT,
		ip_down_size		INT,
		retrans_in_size		INT,
		retrans_out_size	INT,
		cp_code				INT,
		use_count			INT,
		use_time			INT,
		total_size			INT,
		total_time			INT,
		bill_com_count		INT,
		gw_count			INT,
		content_len			INT,
		tran_complte		INT,
		tran_term_reason	INT,
		audio_up_size		INT,
		audio_down_size		INT,
		video_up_size		INT,
		video_down_size		INT,
		url					varchar(721),
		user_agent			varchar(62),
		host				varchar(62),
		mdn					varchar(17),
		phone_num			varchar(17),
		model				varchar(12),
		packet_count		varchar(94),
		url_cha				INT,
		crt_year			INT NOT NULL,
		crt_time			INT NOT NULL,
		matching_key		INT,
		key idx1 (acct_sess_id),
		key idx2 (min),
		key idx3 (matching_key));
