#!/usr/local/bin/expect -f
#
# This Expect script was generated by autoexpect on Mon Jul 27 13:48:15 2009
# Expect and autoexpect were both written by Don Libes, NIST.
#
# Note that autoexpect does not guarantee a working script.  It
# necessarily has to guess about certain things.  Two reasons a script
# might fail are:
#
# 1) timing - A surprising number of programs (rn, ksh, zsh, telnet,
# etc.) and devices discard or ignore keystrokes that arrive "too
# quickly" after prompts.  If you find your new script hanging up at
# one spot, try adding a short sleep just before the previous send.
# Setting "force_conservative" to 1 (see below) makes Expect do this
# automatically - pausing briefly before sending each character.  This
# pacifies every program I know of.  The -c flag makes the script do
# this in the first place.  The -C flag allows you to define a
# character to toggle this mode off and on.

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

#
# 2) differing output - Some programs produce different output each time
# they run.  The "date" command is an obvious example.  Another is
# ftp, if it produces throughput statistics at the end of a file
# transfer.  If this causes a problem, delete these patterns or replace
# them with wildcards.  An alternative is to use the -p flag (for
# "prompt") which makes Expect only look for the last line of output
# (i.e., the prompt).  The -P flag allows you to define a character to
# toggle this mode off and on.
#
# Read the man page for more info.
#
# -Don


set timeout 3
set send_slow {1 .1}

set side    [lindex $argv 0]

set user    "admin"
set pass    "admin"

if {$side < 1} {
	set host    "192.168.100.22"
} else {
	set host    "192.168.100.21"
}

spawn /usr/bin/telnet $host
match_max 100000
expect -exact "sh: /usr/local/bin/stty: ¾øÀ½\r
Trying $host...\r
Connected to $host.\r
Escape character is '^\]'.\r
\r
Copyright 2008 Sun Microsystems, Inc.  All rights reserved.\r
Use is subject to license terms.\r
\r
\r
Sun(tm) Advanced Lights Out Manager CMT v1.7.3\r
\r
Please login: "
sleep .1
send -s -- "admin\r"
expect -exact "admin\r
Please Enter password: "
sleep .1
send -s -- "a"
expect -exact "*"
sleep .1
send -s -- "d"
expect -exact "*"
sleep .1
send -s -- "m"
expect -exact "*"
sleep .1
send -s -- "i"
expect -exact "*"
sleep .1
send -s -- "n"
expect -exact "*"
sleep .1
send -s -- "\r"
expect -exact "\r
\r
\r
sc> "
sleep .1
send -s -- "showenvironment"
expect -exact "showenvironment"
sleep .1
send -s -- "\r"
expect -exact "\r
sc> "
sleep .1
send -s -- "logout\r"
sleep .1
expect eof
