#!/usr/bin/perl

#----------------------------------
# Step 1 - hello.pl
#----------------------------------
print "---------------------------------------------\n";
print "# First Practice - hello.pl \n";
print "---------------------------------------------\n";
print "Hello Hi~~ *^^*\n";


@a=(1,2,3);
print '@a=',@a; print "\n";
$b=4;
print '$b=',$b; print "\n";
$b=$a;
print '$b=',$b; print "\n";
$b=@a;
print '$b=',$b; print "\n";
$b="@a";
print '$b=',$b; print "\n";
@b=@a;
print '@b=',@b; print "\n";
%b=%a;
print '%b=',%b; print "\n";
$b=$a=5;
print '$b=',$b,',$a=',$a,"\n";
exit;
$a=3-10;
print '$a=3-10=',$a,"\n";
$a=4/10;
print '$a=3/10=',$a,"\n";


$a="hello"."world";
print "$a\n";
$a="hello"x3;
print "$a\n";

print ++($foo=99),"\n";
print ++($foo='a0'),"\n";
print ++($foo='Az'),"\n";
print ++($foo='zzz'),"\n";

$a=1;
$b=2;
$c=0;

$d=$a && $b;
print "$d\n";
$d=$a && $c;
print "$d\n";
$d=$a || $b;
print "$d\n";
$d=$a || $c;
print "$d\n";

exit;

# End Of File --------------------------

@heys= ("hello", "there", "l\'m","O.K.","\n");
print "out1st : ";
print "@heys";

print "out2nd : ";
print @hey;
%fruits=("apple",3,"pear",5,"banana",2);
print "out3rd : ";
print "%fruits\n";

#----------------------------------
# Step 2 - Scalar Variable
#----------------------------------
print "\n";
print "---------------------------------------------\n";
print "# Second Practice - Scalar Variable\n";
print "---------------------------------------------\n";

# scalar
$price = 100000;	
print "$price\n";

# string
$price = "Very expensive.";	
print "$price\n";

# calculate with string ??!!!
$price = "130";
$double = $price*2;
print "$double\n";

#----------------------------------
# Step 3 - Array 
#----------------------------------
print "---------------------------------------------\n";
print "# Third  Practice - Array\n";
print "---------------------------------------------\n";

$ma[0] = 0;
$ma[1] = 5;
$ma[2] = "I do not want a number but a long long long string!";
$ma[3] = 300;

print $ma[2],"\n";
print "$ma[2]\n";

print $ma[3],"\n";
print "$ma[3]\n";

$li = $#ma;
print "$li\n";
print "========\n";
print "========\n";
print $li,"\n";
print "========\n";

@arr = ( 1,2,3, "Last member");
$size = @arr;
print "$size\n";

#----------------------------------
# Step 4 - Associative array(hash)
#----------------------------------
print "---------------------------------------------\n";
print "# Fourth Practice - Associative array(hash)\n";
print "---------------------------------------------\n";

@ma = (1,3,5,2,6 );
$fourth = $ma[3]; #2
print "fourth = $fourth\n";

%mh = ( "apple", 3, "pear", 10, "banana", 4, "monkey", 2 );
$howmany = $mh{ "banana" }; #return 4
print "[1]howmany(banana) = $howmany\n";
$howmany = $mh{ "apple" }; #return 3
print "[2]howmany(apple) = $howmany\n";
$howmany = $mh{ "pear" }; #return 10
print "[3]howmany(pear) = $howmany\n";

$mh{ "pear" } = 9; #becomes (..., 3, "pear", 9, "banana... ); 
$howmany = $mh{ "pear" }; #return 9
print "[4]howmany(pear) = $howmany\n";

#----------------------------------
# Step 5 - 'printf'
#----------------------------------
print "---------------------------------------------\n";
print "# Fifth Practice - 'printf'\n";
print "---------------------------------------------\n";

# test...
#print <<end_of_line
#Hi..
#My (nic)name is uamyd0626...hihi
#end_of_line

print "end\n";

print "Say yes or no : ";

$answer=<STDIN>;
print "1\n";
print "$answer";
print "2\n";
print '$answer',"\n";
print "3\n";

print `pwd`;# 'pwd' !! 

@heys=( "Hello", "three", "l\'m", "O.K.", "\n" );
print "@heys";
print @heys;
%fruits=(1,"abdncd", "pear", 2, "banana", 2 );
print "%fruits\n";
print @fruits{1},"\n";
print @fruits{"pear"},"\n";
print @fruits{"banana"},"\n";

print "------------------------------\n";

$a = "H A C K E R      ";
$len = (length $a)-1;

print "$a\r";

#for( 0..3)
#{
	for( 0..$len)
	{
		$s1 = substr($a, 0, $_ );
		print "s1=$s1\n";
		#$s2 = substr($a, $_+1 );
		#print "s2=$s2\n";
		#print "s2s1=$s2$s1\n";
		#print "$s2$s1\r";
		#sleep 1;
	}
#}
print "---------------\n";
for(0..$len){
	$s3 =substr($a,1,$_);
	print "s3=$s3\n";
}
print "---------------\n";
for(0..$len){
	$s4 =substr($a,2,$_);
	print "s4=$s4\n";
}
print "\n";

$sd = 1234;
print '$sd = ', "$sd\n";
print '$sd = ', '$sd\n',"\n";

print `pwd`;





