#ifndef __PROC_ID_H__
#define __PROC_ID_H__

/*
	Process Sequence ID List
*/

enum _en_seq_proc_id {
	
	SEQ_PROC_FIRST = 1,
	SEQ_PROC_A_SIP = SEQ_PROC_FIRST,	/* 0 은 filter 쪽에서 ETC 로 빠짐 */
	SEQ_PROC_A_SIPT,
	SEQ_PROC_A_SIPM,
	SEQ_PROC_A_JNC,
	SEQ_PROC_A_IV,
	SEQ_PROC_A_ONLINE,
	SEQ_PROC_A_DNS,
	SEQ_PROC_A_FTP,
	SEQ_PROC_A_WAP20,

	//10
	SEQ_PROC_A_WIPI,
	SEQ_PROC_A_2G,
	SEQ_PROC_A_JAVA,
	SEQ_PROC_A_VOD,
	SEQ_PROC_A_MMS,
	SEQ_PROC_A_FV,
	SEQ_PROC_A_EMS,
	SEQ_PROC_A_FB,
	SEQ_PROC_A_XCAP,
	SEQ_PROC_A_WIDGET,

	//20
	SEQ_PROC_A_MSRPM,
	SEQ_PROC_A_MSRPT,
	SEQ_PROC_A_VT,
	SEQ_PROC_A_SCTP,
	SEQ_PROC_A_DIAMETER,
	SEQ_PROC_A_RADIUS,
	SEQ_PROC_A_IM,
	SEQ_PROC_A_UDP,
	SEQ_PROC_A_L2TP,

	//29
	SEQ_PROC_A_HTTP, SEQ_PROC_A_HTTP0 = SEQ_PROC_A_HTTP,
	SEQ_PROC_A_HTTP1,
	SEQ_PROC_A_HTTP2,
	SEQ_PROC_A_HTTP3,
	SEQ_PROC_A_HTTP4,

	//34
	SEQ_PROC_A_CALL, SEQ_PROC_A_CALL0 = SEQ_PROC_A_CALL,
	SEQ_PROC_A_CALL1,
	SEQ_PROC_A_CALL2,
	SEQ_PROC_A_CALL3,
	SEQ_PROC_A_CALL4,

	//39
	SEQ_PROC_A_TCP, SEQ_PROC_A_TCP0 = SEQ_PROC_A_TCP,
	SEQ_PROC_A_TCP1,
	SEQ_PROC_A_TCP2,
	SEQ_PROC_A_TCP3,
	SEQ_PROC_A_TCP4,

	//44
	SEQ_PROC_A_ITCP, SEQ_PROC_A_ITCP0 = SEQ_PROC_A_ITCP,
	SEQ_PROC_A_ITCP1,
	SEQ_PROC_A_ITCP2,
	SEQ_PROC_A_ITCP3,
	SEQ_PROC_A_ITCP4,
	
	//49
	SEQ_PROC_A_INET, SEQ_PROC_A_INET0 = SEQ_PROC_A_INET,
	SEQ_PROC_A_INET1,
	SEQ_PROC_A_INET2,
	SEQ_PROC_A_INET3,
	SEQ_PROC_A_INET4,


	//54
	SEQ_PROC_A_IHTTP,	SEQ_PROC_A_IHTTP0 = SEQ_PROC_A_IHTTP,
	SEQ_PROC_A_IHTTP1,
	SEQ_PROC_A_IHTTP2,
	SEQ_PROC_A_IHTTP3,
	SEQ_PROC_A_IHTTP4,

	//59
	SEQ_PROC_A_RP,		SEQ_PROC_A_RP0 =  SEQ_PROC_A_RP,
	SEQ_PROC_A_RP1,
	SEQ_PROC_A_RP2,
	SEQ_PROC_A_RP3,
	SEQ_PROC_A_RP4,

	//64
	SEQ_PROC_A_GRE,		SEQ_PROC_A_GRE0 = SEQ_PROC_A_GRE,
	SEQ_PROC_A_GRE1,
	SEQ_PROC_A_GRE2,
	SEQ_PROC_A_GRE3,
	SEQ_PROC_A_GRE4,

	//69
	SEQ_PROC_PRE_A,
	SEQ_PROC_CAPD,

	//71
	SEQ_PROC_A_RPPI,	SEQ_PROC_A_RPPI0 = SEQ_PROC_A_RPPI,
	SEQ_PROC_A_RPPI1,
	SEQ_PROC_A_RPPI2,
	SEQ_PROC_A_RPPI3,
	SEQ_PROC_A_RPPI4,

	//76
	SEQ_PROC_M_LOG,
	SEQ_PROC_O_SVCMON,
	SEQ_PROC_M_SVCMON,
	SEQ_PROC_SI_SVCMON,

	//80
	SEQ_PROC_A_ROAM,
	SEQ_PROC_M_TRACE,
	SEQ_PROC_SI_DB,
	SEQ_PROC_SI_LOG,
	SEQ_PROC_CI_LOG,
	SEQ_PROC_MOND,
	SEQ_PROC_CHGSVCM,

	/* OAM PROCESS */
	//87
	SEQ_PROC_CHSMD,
	SEQ_PROC_COND,
	SEQ_PROC_ALMD,
	SEQ_PROC_MMCD,
	SEQ_PROC_SI_SVC,
	SEQ_PROC_CI_SVC,
	//93
	SEQ_PROC_FSTAT,
	SEQ_PROC_S_MNG,
	SEQ_PROC_QMON,
	SEQ_PROC_SI_NMS,
	SEQ_PROC_TIFB,
	SEQ_PROC_SNMPIF,

	SEQ_PROC_LAST
};

#endif /* __PROC_ID_H__ */
