#ifndef __SSHM_ID_H__
#define __SSHM_ID_H__


enum _en_oam_sshm {
	S_SSHM_DEFINE = 10000,
	S_SSHM_START_KEY_OAM,

	S_SSHM_LOG_LEVEL = S_SSHM_START_KEY_OAM,
	S_SSHM_LOAD,
	S_SSHM_FAULT,
	S_SSHM_FIDB,
	S_SSHM_TRAFFICSTAT,
	S_SSHM_TRAFFICSTAT2,
	S_SSHM_KEEPALIVE,
	S_SSHM_VERSION,
	S_SSHM_TRACE_INFO,
	S_SSHM_A_GNGI,
	S_SSHM_MODELHASH1,
	S_SSHM_MODELHASH2,
	S_SSHM_TAF_FIDB,
	S_SSHM_LOADSTAT,
	S_SSHM_GENINFO,

	//// 아래 key는 그냥 놔둬 주셈 ~ :: TIFB/KillMC.c 에서 사용됨.
	//// 새롭게 define 하기를 원하는 경우, 위 쪽에 정의해주세요.
	S_SSHM_LAST_KEY_OAM
};

enum _en_sshm_id {
	
	S_SSHM_START_KEY = 11000,

	S_SSHM_UTIL = S_SSHM_START_KEY, // 혹시나 다른 것을 먼저 define 하고 싶으시다면, S_SSHM_START_KEY를 처음에 assign 해주세요. 
	S_SSHM_A_VT,
	S_SSHM_A_IM,
	S_SSHM_A_SCTP_ASSOC,
	S_SSHM_A_JNC,
	S_SSHM_VODSESS,
	S_SSHM_RTCPSESS,
	S_SSHM_A_MSRPM,
	S_SSHM_A_MSRPT,
	S_SSHM_A_IV,

	S_SSHM_SIPT_LIST,
	S_SSHM_A_SIPT,
	S_SSHM_A_SIPM,
	S_SSHM_SIPT_SESS,
	S_SSHM_A_ONLINE,
	S_SSHM_DIAMETER,
	S_SSHM_RADIUS,
	S_SSHM_A_FTP,
	S_SSHM_DNS_SESS,
	S_SSHM_CONTROL,

	S_SSHM_A_L2TP,
	S_SSHM_TUNNELID,
	S_SSHM_SESSION,
	S_SSHM_FLT_INFO,

	S_SSHM_A_CALL, 		S_SSHM_A_CALL0 		= S_SSHM_A_CALL,
	S_SSHM_TCP_LIST,	S_SSHM_TCP_LIST0	= S_SSHM_TCP_LIST,
	S_SSHM_A_TCP, 		S_SSHM_A_TCP0 		= S_SSHM_A_TCP,
	S_SSHM_ITCP_LIST, 	S_SSHM_ITCP_LIST0 	= S_SSHM_ITCP_LIST,
	S_SSHM_ISESS_KEY, 	S_SSHM_ISESS_KEY0 	= S_SSHM_ISESS_KEY,
	S_SSHM_A_ITCP, 		S_SSHM_A_ITCP0 		= S_SSHM_A_ITCP,
	S_SSHM_SESS_KEY, 	S_SSHM_SESS_KEY0 	= S_SSHM_SESS_KEY,

	S_SSHM_A_TSESS, 	S_SSHM_A_TSESS0 	= S_SSHM_A_TSESS,
	S_SSHM_A_HTTP, 		S_SSHM_A_HTTP0 		= S_SSHM_A_HTTP,
	S_SSHM_A_ITSESS, 	S_SSHM_A_ITSESS0 	= S_SSHM_A_ITSESS,
	S_SSHM_A_IHTTP, 	S_SSHM_A_IHTTP0 	= S_SSHM_A_IHTTP,
	S_SSHM_INETHASH, 	S_SSHM_INETHASH0 	 = S_SSHM_INETHASH,
	S_SSHM_INETCALL, 	S_SSHM_INETCALL0 	 = S_SSHM_INETCALL,
	S_SSHM_A11_PSESS, 	S_SSHM_A11_PSESS0 	 = S_SSHM_A11_PSESS,
	S_SSHM_A11_PSESS1,
	S_SSHM_A11_PSESS2,
	S_SSHM_A11_PSESS3,
	S_SSHM_A11_PSESS4,
	S_SSHM_A11_GREENTRY,S_SSHM_A11_GREENTRY0 = S_SSHM_A11_GREENTRY,
	S_SSHM_A11_GREENTRY1,
	S_SSHM_A11_GREENTRY2,
	S_SSHM_A11_GREENTRY3,
	S_SSHM_A11_GREENTRY4,
	S_SSHM_A11CALL,
	S_SSHM_LPREA_HASH,

	S_SSHM_LPREA_SCTP,
	S_SSHM_IP_FRAG,
	S_SSHM_SUBSYS,
	S_SSHM_IPPOOL_BIT,
	S_SSHM_WATCH_FILTER,

	S_SSHM_A_RPPI,		S_SSHM_A_RPPI0		= S_SSHM_A_RPPI,
	S_SSHM_A_RPPI1,
	S_SSHM_A_RPPI2,
	S_SSHM_A_RPPI3,
	S_SSHM_A_RPPI4,

	S_SSHM_A_ROAM,
	S_SSHM_MON_TOTAL,
	S_SSHM_MON_TOTAL_1MIN,

	S_SSHM_SERVTRACE_INFO,
	S_SSHM_TRACE_FILE,
	S_SSHM_SERVTRACE_FILE,

	//// 아래 key는 그냥 놔둬 주셈 ~ :: TIFB/KillMC.c 에서 사용됨.
	//// 새롭게 define 하기를 원하는 경우, 위 쪽에 정의해주세요.
	S_SSHM_LAST_KEY
	
};

#endif /* __SSHM_ID_H__ */
