SELECT HIS_TABLE.USERNAME,HIS_TABLE.TIME,IFNULL(HIS_TABLE.USERIP,0),HIS_TABLE.COMMAND 
  FROM (
	SELECT 
		@ROWNUM := @ROWNUM + 1 AS ROWNUM, 
		SYS_MMCD_MSG.USERNAME AS USERNAME, 
		SYS_MMCD_MSG.USERIP AS USERIP, 
		SYS_MMCD_MSG.TIME AS TIME, 
		SYS_MMCD_MSG.COMMAND AS COMMAND 
	  FROM SYS_MMCD_MSG, (SELECT @ROWNUM := 0) R 
	 WHERE ((TIME >= 1282955955) AND (TIME <= 1282959555)) 
	 GROUP BY SYS_MMCD_MSG.USERNAME,SYS_MMCD_MSG.USERIP,SYS_MMCD_MSG.TIME,SYS_MMCD_MSG.COMMAND 
	 ORDER BY SYS_MMCD_MSG.TIME ) HIS_TABLE 
 WHERE HIS_TABLE.ROWNUM > 36

SELECT HIS_TABLE.USERNAME,HIS_TABLE.TIME,IFNULL(HIS_TABLE.USERIP,0),HIS_TABLE.COMMAND 
  FROM (
	SELECT 
		@ROWNUM := @ROWNUM + 1 AS ROWNUM, 
		SYS_MMCD_MSG.USERNAME AS USERNAME, 
		SYS_MMCD_MSG.USERIP AS USERIP, 
		SYS_MMCD_MSG.TIME AS TIME, 
		SYS_MMCD_MSG.COMMAND AS COMMAND 
	  FROM SYS_MMCD_MSG, (SELECT @ROWNUM := 0) R 
	 WHERE (TIME = 1282959555 ) 
	 GROUP BY SYS_MMCD_MSG.USERNAME,SYS_MMCD_MSG.USERIP,SYS_MMCD_MSG.TIME,SYS_MMCD_MSG.COMMAND 
	 ORDER BY SYS_MMCD_MSG.TIME ) HIS_TABLE 
 WHERE HIS_TABLE.ROWNUM > 36
