#ifndef __COMM_ALMSTS_MSGCODE_H__LMCODE_SFM
#define __COMM_ALMSTS_MSGCODE_H__

//------------------------------------------------------------------------------
// 장애 메시지 코드 값을 정의한다.
//------------------------------------------------------------------------------

/* by sjjeon 2009/08/13 
   레벨별 알람코드는 해당 알람 코드의 MINOR: +100, MAJOR: +200, CRITICAL: +300
   추가한다.
*/

#define ALMCODE_STS_MINOR 				100
#define ALMCODE_STS_MAJOR 				200
#define ALMCODE_STS_CRITICAL			300


/* common alm */
#define ALMCODE_SFM_CPU_USAGE			1000 // CPU 사용률 알람
#define ALMCODE_SFM_MEMORY_USAGE		1001 // 메모리 사용률 알람
#define ALMCODE_SFM_DISK_USAGE			1002 // 디스크 사용률 알람
#define ALMCODE_SFM_LAN					1003 // LAN connection 상태 알람
#define ALMCODE_SFM_PROCESS				1004 // 프로세스 상태 알람



/* spec alm */
#define ALMCODE_SFM_LINK				1005 // LINK connection 상태 알람
#define ALMCODE_SFM_DB_REP    			1006 // DB Replication state
#define ALMCODE_SFM_DB_REP_GAP			1007 // DB Replication Gap state
#define ALMCODE_SFM_BSD					1009 // hardware 의 알람 발생시
#define ALMCODE_SFM_SERVER_CONN			1010 // hardware 의 알람 발생시
#define ALMCODE_SFM_CALL_INFO			1011 // hardware 의 알람 발생시


/* by helca */
/* duplication alm*/
#define ALMCODE_SFM_DUPLICATION			1012 // Duplication 상태 알람
#define ALMCODE_SFM_HEARTBEAT			1013 // HEARTBEAT 상태 알람
#define ALMCODE_SFM_OOS					1014 // OOS 상태 알람
#define ALMCODE_SFM_SUCCESS_RATE		1015 // SuccessRate 상태 알람
#define ALMCODE_SFM_SESS_LOAD			1016 // Session에 대한 Load상태 알람
#define ALMCODE_SFM_RMT_DB_STS			1017 // Remote DB 상태 알람
#define ALMCODE_SFM_RMT_LAN				1018 // Remote LAN Connection 상태 알람
#define ALMCODE_SFM_OPT_LAN				1019 // Optical LAN Connection 상태 알람
#define ALMCODE_SFM_HWNTP				1020 // hwNTP 상태 알람

/* TAP */
//#define ALMCODE_SFM_PD_CPU_USAGE		1021 // TAP 사용률 알람
//#define ALMCODE_SFM_PD_MEMORY_USAGE		1022 // TAP 메모리 사용률 알람
//#define ALMCODE_SFM_PD_FAN_USAGE		1023 // TAP 팬 사용률 알람
//#define ALMCODE_SFM_PD_GIGA_USAGE		1024 // TAP LAN connection 상태 알람
#define ALMCODE_SFM_TAP_CPU_USAGE		1021 // TAP 사용률 알람
#define ALMCODE_SFM_TAP_MEMORY_USAGE	1022 // TAP 메모리 사용률 알람
#define ALMCODE_SFM_TAP_FAN_USAGE		1023 // TAP 팬 사용률 알람
#define ALMCODE_SFM_TAP_PORT_STS		1024 // TAP Port 상태 알람

#define ALMCODE_SFM_RSRC_LOAD			1025

// HPUX_HW
#define ALMCODE_SFM_HPUX_HW				1026

#define ALMCODE_SFM_QUEUE_LOAD			1027 // Queue load 상태 알람 

#define ALMCODE_SFM_DUAL_ACT			1028
#define ALMCODE_SFM_DUAL_STD			1029
#define ALMCODE_SFM_DUAL_STS_QRY_TIME_OUT	1030

#define ALMCODE_SFM_TAP_MGMT_STS		1031 // TAP Management 상태 알람
#define ALMCODE_SFM_L2SW_MGMT_STS		1032 // L2 Switch Management 상태 알람
#define ALMCODE_SFM_PROCESS_RLEG0       1033 /* RLEG0~4 added by dcham 2011.04.26 */
#define ALMCODE_SFM_PROCESS_RLEG1       1034
#define ALMCODE_SFM_PROCESS_RLEG2       1035
#define ALMCODE_SFM_PROCESS_RLEG3       1036
#define ALMCODE_SFM_PROCESS_RLEG4       1037

/* udr collector */
#define ALMCODE_SFM_MP_FTPSVR_STS		1041

#define ALMCODE_SFM_LOGOUT_SUCCESS_RATE	1042 /* LOGOUT SUCCESS RATE STAT , added by uamyd 20110424 */
#define ALMCODE_SFM_SM_CONN_STS			1043 /* SM Connection Link Status Alarm, added by uamyd 20110425 */

#define ALMCODE_SFM_PROCESS_SCEM		1044 // OMP SCEM 상태알람 added by dcham 2011.04.22
#define ALMCODE_SFM_PROCESS_CSCM        1045 // OMP CSCM 상태알람 added by dcham 2011.04.22
#define ALMCODE_SFM_PROCESS_DIRM		1046 // OMP DIRM 상태알람 added by dcham 2011.04.22
#define ALMCODE_SFM_TAP_POWER_STS       1047 // DIRECTOR POWER 상태 알람 added by dcham 2011.04.22
/* SCE DEVICE ALARM CODE */
//#define ALMCODE_SFM_SCE_UNKNOWN			1050  ==> ALMCODE_SFM_UNKNOWN 9999
#define ALMCODE_SFM_SCE_CPU_USAGE		1051
#define ALMCODE_SFM_SCE_MEM_USAGE		1052
#define ALMCODE_SFM_SCE_DISK_USAGE		1053
#define ALMCODE_SFM_SCE_PORT_USAGE		1054
#define ALMCODE_SFM_SCE_FAN_USAGE		1055
#define ALMCODE_SFM_SCE_PWR_USAGE		1056
#define ALMCODE_SFM_SCE_RDR_CONN_STS	1061
#define ALMCODE_SFM_SCE_SYS_STS			1062
#define ALMCODE_SFM_SCE_TEMP_STS		1063

/* L2 DEVICE ALARM CODE */
#define ALMCODE_SFM_L2SW_CPU_USAGE		1057
#define ALMCODE_SFM_L2SW_MEMORY_USAGE	1058
#define ALMCODE_SFM_L2SW_LAN_STS		1059

/* CPS OVER ALARM CODE */
#define ALMCODE_SFM_CPS_OVER_INFO		1060 // CPS OVER 상태 알람

/* TPS OVER ALARM CODE */
#define ALMCODE_SFM_TPS_INFO       1064 // TPS OVER 상태 알람, 20110525 added by dcham, TPS(Transaction Per Second)

/* SVC OVER ALARM CODE */
#define ALMCODE_SFM_SVC_OVER_INFO		1070 // SVC OVER 상태 알람

/* sjjeon : 프로세스 장애 메시지 코드 추가.*/
#define ALMCODE_SFM_PROCESS_SAMD		1071 // OMP,MP SAMD 상태알람
#define ALMCODE_SFM_PROCESS_IXPC		1072 // OMP,MP IXPC 상태알람
#define ALMCODE_SFM_PROCESS_FIMD		1073 // OMP FIMD 상태알람
#define ALMCODE_SFM_PROCESS_COND		1074 // OMP COND 상태알람
#define ALMCODE_SFM_PROCESS_STMD		1075 // OMP STMD 상태알람
#define ALMCODE_SFM_PROCESS_MMCD		1076 // OMP MMCD 상태알람
#define ALMCODE_SFM_PROCESS_MCMD		1077 // OMP MCMD 상태알람
#define ALMCODE_SFM_PROCESS_NMSIF		1078 // OMP NMSIF 상태알람
#define ALMCODE_SFM_PROCESS_CDELAY		1079 // OMP CDELAY 상태알람
#define ALMCODE_SFM_PROCESS_HAMON		1080 // OMP HAMON 상태알람
#define ALMCODE_SFM_PROCESS_MMCR		1081 // MP MMCR 상태알람
#define ALMCODE_SFM_PROCESS_RDRANA		1082 // MP RDRANA 상태알람
#define ALMCODE_SFM_PROCESS_RLEG		1083 // MP RLEG 상태알람
#define ALMCODE_SFM_PROCESS_SMPP		1084 // MP SMPP 상태알람
#define ALMCODE_SFM_PROCESS_PANA		1085 // MP PANA 상태알람
#define ALMCODE_SFM_PROCESS_RANA		1086 // MP RANA 상태알람
#define ALMCODE_SFM_PROCESS_RDRCAPD		1087 // MP RDRCAPD 상태알람
#define ALMCODE_SFM_PROCESS_CAPD		1088 // MP CAPD 상태알람


/* sjjeon : SCM LAN TAP 연결 장애 메시지 코드 추가.*/
#define ALMCODE_SFM_LAN_TAP_CONN		1091 // LAN 의 TAP connection 상태 알람

/* Mirror port 장애 메시지 코드 추가. */
#define ALMCODE_SFM_MIRROR_PORT			1092 // MIRROR PORT

#define ALMCODE_SFM_SCE_USER_USAGE		1093
/* hjjung_20100823 */
#define ALMCODE_SFM_LEG_SESSION_USAGE	1094

// 20100915 by dcham
#define ALMCODE_SFM_SCM_FAULTED         1095

#define ALMCODE_SFM_LOGON_SUCCESS_RATE	1096 /* LOGON SUCCESS RATE STAT , added by uamyd 20110209 */


/* SYSTEM ACTIVE/STANBY alm */
// 두 시스템의 standby/active 상태가 같을때의 알람
#define ALMCODE_SFM_ACTIVE			1400

/* NMS */
#define ALMCODE_NMS_CONNECT			3500

/* RULE SET */
//#define APPLY_RULESET_COMPLETE_ALARM	3600
//#define APPLY_RULESET_COMPLETE_ALARM	8000 /*완료 */
#define APPLY_RULESET_SCEA_PROGRESS_ALARM	8001 /*SCEA 진행중 */
#define APPLY_RULESET_SCEB_PROGRESS_ALARM	8002 /*SCEB 진행중 */
#define APPLY_RULESET_ALL_PROGRESS_ALARM	8003 /*ALL 진행중. */
#define APPLY_RULESET_SCEA_COMPLETE_ALARM	8011 /*SCEA 완료 */
#define APPLY_RULESET_SCEB_COMPLETE_ALARM	8012 /*SCEB 완료 */
#define APPLY_RULESET_SCEA_FAIL_ALARM		8021 /*SCEB 실패 */
#define APPLY_RULESET_SCEB_FAIL_ALARM		8022 /*SCEB 실패 */

#define ALMCODE_SFM_UNKNOWN					9999 /*정의되지 않은 알람코드 */	
//------------------------------------------------------------------------------
// 상태 메시지 코드 값을 정의한다.
//------------------------------------------------------------------------------


#define STSCODE_SFM_SYS_LEVEL_CHANGE		2000 // 시스템 전체 장애 등급이 변경된 경우의 알람

//process 가 keepalive 하지 못할때의 알람
#define	STSCODE_SFM_WATCHDOG_REPORT		2001

// hardware 상태 알람 해제시
#define STSCODE_SFM_HPUX_HW			2002 

//1. altibase log report 메세지를 뿌려줄때
//2. DB Replication 이 clear 되었을때
#define STSCODE_SFM_PROCESS			2003

// Queue cnt가 200,000 이상이 쌓여 clear시
#define STSCODE_SFM_QUEUE_CLEAR                 2004

#define STSCODE_SFM_SYS_DUPLICATION_STS		    5000 // by helca 08.15
#define STSCODE_SFM_SYS_SUCCRATE_STS		    6000 // by helca 08.28
#define STSCODE_SFM_SYS_NMSIF_STS		    7000 // by helca 10.30
#define STSCODE_SFM_SYS_UAWAP_TRANSLOG_FILE_STS     8000 // by helca 12.19
//------------------------------------------------------------------------------
// OMP의 통계 메시지 코드 값을 정의한다.
//------------------------------------------------------------------------------

// 주기적 통계 메시지의 상태 메시지 코드는 comm_msgtypes.h에 정의되어 있는
// 메시지 ID에 2000을 더하면 된다.
#define STSCODE_STM_PERIODIC_FAULT_MINUTE           3000 //안쓰는데
#define STSCODE_STM_PERIODIC_FAULT_HOUR             3001
#define STSCODE_STM_PERIODIC_FAULT_DAY              3002
#define STSCODE_STM_PERIODIC_FAULT_WEEK             3003
#define STSCODE_STM_PERIODIC_FAULT_MONTH            3004
#define STSCODE_STM_SCHEDULE_FAULT                  3005

#define STSCODE_STM_PERIODIC_LOAD_MINUTE            3010 //안쓰는데
#define STSCODE_STM_PERIODIC_LOAD_HOUR              3011
#define STSCODE_STM_PERIODIC_LOAD_DAY               3012
#define STSCODE_STM_PERIODIC_LOAD_WEEK              3013
#define STSCODE_STM_PERIODIC_LOAD_MONTH             3014
#define STSCODE_STM_SCHEDULE_LOAD                   3015

#define STSCODE_STM_PERIODIC_LINK_MINUTE            3020 //안쓰는데
#define STSCODE_STM_PERIODIC_LINK_HOUR              3021
#define STSCODE_STM_PERIODIC_LINK_DAY               3022
#define STSCODE_STM_PERIODIC_LINK_WEEK              3023
#define STSCODE_STM_PERIODIC_LINK_MONTH             3024
#define STSCODE_STM_SCHEDULE_LINK                   3025

#define STSCODE_STM_PERIODIC_LEG_MINUTE            	3030 //안쓰는데
#define STSCODE_STM_PERIODIC_LEG_HOUR              	3031
#define STSCODE_STM_PERIODIC_LEG_DAY               	3032
#define STSCODE_STM_PERIODIC_LEG_WEEK              	3033
#define STSCODE_STM_PERIODIC_LEG_MONTH             	3034
#define STSCODE_STM_SCHEDULE_LEG                   	3035

#define STSCODE_STM_PERIODIC_LOGON_MINUTE           3040 //안쓰는데
#define STSCODE_STM_PERIODIC_LOGON_HOUR             3041
#define STSCODE_STM_PERIODIC_LOGON_DAY              3042
#define STSCODE_STM_PERIODIC_LOGON_WEEK             3043
#define STSCODE_STM_PERIODIC_LOGON_MONTH            3044
#define STSCODE_STM_SCHEDULE_LOGON                  3045

#define STSCODE_STM_PERIODIC_RULESET_HOUR         	3051
#define STSCODE_STM_PERIODIC_RULESET_DAY          	3052
#define STSCODE_STM_PERIODIC_RULESET_WEEK         	3053
#define STSCODE_STM_PERIODIC_RULESET_MONTH        	3054
#define STSCODE_STM_SCHEDULE_RULESET              	3055

#define STSCODE_STM_PERIODIC_RULEENT_HOUR         	3061
#define STSCODE_STM_PERIODIC_RULEENT_DAY          	3062
#define STSCODE_STM_PERIODIC_RULEENT_WEEK         	3063
#define STSCODE_STM_PERIODIC_RULEENT_MONTH        	3064
#define STSCODE_STM_SCHEDULE_RULEENT              	3065

#define STSCODE_STM_PERIODIC_SMS_HOUR         		3071
#define STSCODE_STM_PERIODIC_SMS_DAY          		3072
#define STSCODE_STM_PERIODIC_SMS_WEEK         		3073
#define STSCODE_STM_PERIODIC_SMS_MONTH        		3074
#define STSCODE_STM_SCHEDULE_SMS              		3075

#define STSCODE_STM_PERIODIC_DEL_HOUR         		3081
#define STSCODE_STM_PERIODIC_DEL_DAY          		3082
#define STSCODE_STM_PERIODIC_DEL_WEEK         		3083
#define STSCODE_STM_PERIODIC_DEL_MONTH        		3084
#define STSCODE_STM_SCHEDULE_DEL              		3085

#define STSCODE_STM_PERIODIC_FLOW_HOUR             	3091
#define STSCODE_STM_PERIODIC_FLOW_DAY              	3092
#define STSCODE_STM_PERIODIC_FLOW_WEEK             	3093
#define STSCODE_STM_PERIODIC_FLOW_MONTH            	3094
#define STSCODE_STM_SCHEDULE_FLOW                  	3095

/*
#define STSCODE_STM_PERIODIC_RULECNT_HOUR           3021
#define STSCODE_STM_PERIODIC_RULECNT_DAY            3022
#define STSCODE_STM_PERIODIC_RULECNT_WEEK           3023
#define STSCODE_STM_PERIODIC_RULECNT_MONTH          3024
#define STSCODE_STM_SCHEDULE_RULECNT                3025

#define STSCODE_STM_PERIODIC_PUR_HOUR           	3031
#define STSCODE_STM_PERIODIC_PUR_DAY            	3032
#define STSCODE_STM_PERIODIC_PUR_WEEK           	3033
#define STSCODE_STM_PERIODIC_PUR_MONTH          	3034
#define STSCODE_STM_SCHEDULE_PUR                	3035

#define STSCODE_STM_PERIODIC_RULEUSER_HOUR         	3041
#define STSCODE_STM_PERIODIC_RULEUSER_DAY          	3042
#define STSCODE_STM_PERIODIC_RULEUSER_WEEK         	3043
#define STSCODE_STM_PERIODIC_RULEUSER_MONTH        	3044
#define STSCODE_STM_SCHEDULE_RULEUSER              	3045
*/


/*
#define STSCODE_STM_PERIODIC_SCIB_MINUTE            3020 //안쓰는데
#define STSCODE_STM_PERIODIC_SCIB_HOUR              3021
#define STSCODE_STM_PERIODIC_SCIB_DAY               3022
#define STSCODE_STM_PERIODIC_SCIB_WEEK              3023
#define STSCODE_STM_PERIODIC_SCIB_MONTH             3024
#define STSCODE_STM_SCHEDULE_SCIB                   3025

#define STSCODE_STM_PERIODIC_SCIB_MINUTE            3020 //안쓰는데
#define STSCODE_STM_PERIODIC_SCIB_HOUR              3021
#define STSCODE_STM_PERIODIC_SCIB_DAY               3022
#define STSCODE_STM_PERIODIC_SCIB_WEEK              3023
#define STSCODE_STM_PERIODIC_SCIB_MONTH             3024
#define STSCODE_STM_SCHEDULE_SCIB                   3025

#define STSCODE_STM_PERIODIC_RCIF_MINUTE            3030 //안쓰는데
#define STSCODE_STM_PERIODIC_RCIF_HOUR              3031
#define STSCODE_STM_PERIODIC_RCIF_DAY               3032
#define STSCODE_STM_PERIODIC_RCIF_WEEK              3033
#define STSCODE_STM_PERIODIC_RCIF_MONTH             3034
#define STSCODE_STM_SCHEDULE_RCIF                   3035

#define STSCODE_STM_PERIODIC_SCPIF_MINUTE            3040 //안쓰는데
#define STSCODE_STM_PERIODIC_SCPIF_HOUR              3041
#define STSCODE_STM_PERIODIC_SCPIF_DAY               3042
#define STSCODE_STM_PERIODIC_SCPIF_WEEK              3043
#define STSCODE_STM_PERIODIC_SCPIF_MONTH             3044
#define STSCODE_STM_SCHEDULE_SCPIF                   3045

#define STSCODE_STM_PERIODIC_WISE_MINUTE            3050 //안쓰는데
#define STSCODE_STM_PERIODIC_WISE_HOUR              3051
#define STSCODE_STM_PERIODIC_WISE_DAY               3052
#define STSCODE_STM_PERIODIC_WISE_WEEK              3053
#define STSCODE_STM_PERIODIC_WISE_MONTH             3054
#define STSCODE_STM_SCHEDULE_WISE                   3055

#define STSCODE_STM_PERIODIC_DB_MINUTE            3060 //안쓰는데
#define STSCODE_STM_PERIODIC_DB_HOUR              3061
#define STSCODE_STM_PERIODIC_DB_DAY               3062
#define STSCODE_STM_PERIODIC_DB_WEEK              3063
#define STSCODE_STM_PERIODIC_DB_MONTH             3064
#define STSCODE_STM_SCHEDULE_DB                   3065

#define STSCODE_STM_PERIODIC_OB_MINUTE            3070 //안쓰는데
#define STSCODE_STM_PERIODIC_OB_HOUR              3071
#define STSCODE_STM_PERIODIC_OB_DAY               3072
#define STSCODE_STM_PERIODIC_OB_WEEK              3073
#define STSCODE_STM_PERIODIC_OB_MONTH             3074
#define STSCODE_STM_SCHEDULE_OB                   3075

#define STSCODE_STM_PERIODIC_OBC_MINUTE           3080 //안쓰는데
#define STSCODE_STM_PERIODIC_OBC_HOUR             3081
#define STSCODE_STM_PERIODIC_OBC_DAY              3082
#define STSCODE_STM_PERIODIC_OBC_WEEK             3083
#define STSCODE_STM_PERIODIC_OBC_MONTH            3084
#define STSCODE_STM_SCHEDULE_OBC                  3085

#define STSCODE_STM_PERIODIC_IPAF_MINUTE     	3790
#define STSCODE_STM_PERIODIC_IPAF_HOUR    	3791
#define STSCODE_STM_PERIODIC_IPAF_DAY     	3792
#define STSCODE_STM_PERIODIC_IPAF_WEEK    	3793
#define STSCODE_STM_PERIODIC_IPAF_MONTH      	3794
#define STSCODE_STM_SCHEDULE_IPAF         	3795

#define STSCODE_STM_PERIODIC_AAA_MINUTE     	3800
#define STSCODE_STM_PERIODIC_AAA_HOUR    	3801
#define STSCODE_STM_PERIODIC_AAA_DAY     	3802
#define STSCODE_STM_PERIODIC_AAA_WEEK    	3803
#define STSCODE_STM_PERIODIC_AAA_MONTH      	3804
#define STSCODE_STM_SCHEDULE_AAA         	3805

#define STSCODE_STM_PERIODIC_AN_AAA_MINUTE     	3900
#define STSCODE_STM_PERIODIC_AN_AAA_HOUR    	3901
#define STSCODE_STM_PERIODIC_AN_AAA_DAY     	3902
#define STSCODE_STM_PERIODIC_AN_AAA_WEEK    	3903
#define STSCODE_STM_PERIODIC_AN_AAA_MONTH      	3904
#define STSCODE_STM_SCHEDULE_AN_AAA         	3905

#if 0 
#define STSCODE_STM_PERIODIC_MEAN_MINUTE    	3810 
#define STSCODE_STM_PERIODIC_MEAN_HOUR    	3811
#define STSCODE_STM_PERIODIC_MEAN_DAY     	3812
#define STSCODE_STM_PERIODIC_MEAN_WEEK    	3813
#define STSCODE_STM_PERIODIC_MEAN_MONTH     	3814
#define STSCODE_STM_SCHEDULE_MEAN         	3815
#endif

#define STSCODE_STM_PERIODIC_UAWAP_MINUTE	3820 
#define STSCODE_STM_PERIODIC_UAWAP_HOUR		3821
#define STSCODE_STM_PERIODIC_UAWAP_DAY		3822
#define STSCODE_STM_PERIODIC_UAWAP_WEEK		3823
#define STSCODE_STM_PERIODIC_UAWAP_MONTH	3824
#define STSCODE_STM_SCHEDULE_UAWAP		3825

#define STSCODE_STM_PERIODIC_SVC_TR_MINUTE	3830 
#define STSCODE_STM_PERIODIC_SVC_TR_HOUR	3831
#define STSCODE_STM_PERIODIC_SVC_TR_DAY		3832
#define STSCODE_STM_PERIODIC_SVC_TR_WEEK	3833
#define STSCODE_STM_PERIODIC_SVC_TR_MONTH	3834
#define STSCODE_STM_SCHEDULE_SVC_TR		3835

#define STSCODE_STM_PERIODIC_RADIUS_MINUTE	3840 
#define STSCODE_STM_PERIODIC_RADIUS_HOUR	3841
#define STSCODE_STM_PERIODIC_RADIUS_DAY		3842
#define STSCODE_STM_PERIODIC_RADIUS_WEEK	3843
#define STSCODE_STM_PERIODIC_RADIUS_MONTH	3844
#define STSCODE_STM_SCHEDULE_RADIUS		3845

#define STSCODE_STM_PERIODIC_SVC_TTR_MINUTE	3850 
#define STSCODE_STM_PERIODIC_SVC_TTR_HOUR	3851
#define STSCODE_STM_PERIODIC_SVC_TTR_DAY	3852
#define STSCODE_STM_PERIODIC_SVC_TTR_WEEK	3853
#define STSCODE_STM_PERIODIC_SVC_TTR_MONTH	3854
#define STSCODE_STM_SCHEDULE_SVC_TTR		3855

#define STSCODE_STM_PERIODIC_UDR_MINUTE		3860 
#define STSCODE_STM_PERIODIC_UDR_HOUR		3861
#define STSCODE_STM_PERIODIC_UDR_DAY		3862
#define STSCODE_STM_PERIODIC_UDR_WEEK		3863
#define STSCODE_STM_PERIODIC_UDR_MONTH		3864
#define STSCODE_STM_SCHEDULE_UDR		3865

#define STSCODE_STM_PERIODIC_CDR_MINUTE		3870 
#define STSCODE_STM_PERIODIC_CDR_HOUR		3871
#define STSCODE_STM_PERIODIC_CDR_DAY		3872
#define STSCODE_STM_PERIODIC_CDR_WEEK		3873
#define STSCODE_STM_PERIODIC_CDR_MONTH		3874
#define STSCODE_STM_SCHEDULE_CDR		3875

#define STSCODE_STM_PERIODIC_SVC_TYPE_UDR_MINUTE        4000
#define STSCODE_STM_PERIODIC_SVC_TYPE_UDR_HOUR          4001
#define STSCODE_STM_PERIODIC_SVC_TYPE_UDR_DAY           4002
#define STSCODE_STM_PERIODIC_SVC_TYPE_UDR_WEEK          4003
#define STSCODE_STM_PERIODIC_SVC_TYPE_UDR_MONTH         4004
#define STSCODE_STM_SCHEDULE_SVC_TYPE_UDR               4005

#define STSCODE_STM_PERIODIC_VT_MINUTE  		4010      
#define STSCODE_STM_PERIODIC_VT_HOUR         		4011 
#define STSCODE_STM_PERIODIC_VT_DAY          		4012 
#define STSCODE_STM_PERIODIC_VT_WEEK         		4013 
#define STSCODE_STM_PERIODIC_VT_MONTH        		4014 
#define STSCODE_STM_SCHEDULE_VT  			4015 

#define STSCODE_STM_PERIODIC_SVC_WAP1_MINUTE            4020
#define STSCODE_STM_PERIODIC_SVC_WAP1_HOUR              4021
#define STSCODE_STM_PERIODIC_SVC_WAP1_DAY               4022
#define STSCODE_STM_PERIODIC_SVC_WAP1_WEEK              4023
#define STSCODE_STM_PERIODIC_SVC_WAP1_MONTH             4024
#define STSCODE_STM_SCHEDULE_SVC_WAP1                   4025

#define STSCODE_STM_PERIODIC_SVC_WAP2_MINUTE            4030
#define STSCODE_STM_PERIODIC_SVC_WAP2_HOUR              4031
#define STSCODE_STM_PERIODIC_SVC_WAP2_DAY               4032
#define STSCODE_STM_PERIODIC_SVC_WAP2_WEEK              4033
#define STSCODE_STM_PERIODIC_SVC_WAP2_MONTH             4034
#define STSCODE_STM_SCHEDULE_SVC_WAP2                   4035

#define STSCODE_STM_PERIODIC_SVC_HTTP_MINUTE            4040
#define STSCODE_STM_PERIODIC_SVC_HTTP_HOUR              4041
#define STSCODE_STM_PERIODIC_SVC_HTTP_DAY               4042
#define STSCODE_STM_PERIODIC_SVC_HTTP_WEEK              4043
#define STSCODE_STM_PERIODIC_SVC_HTTP_MONTH             4044
#define STSCODE_STM_SCHEDULE_SVC_HTTP                   4045

#define STSCODE_STM_PERIODIC_SVC_JAVA_MINUTE            4050
#define STSCODE_STM_PERIODIC_SVC_JAVA_HOUR              4051
#define STSCODE_STM_PERIODIC_SVC_JAVA_DAY               4052
#define STSCODE_STM_PERIODIC_SVC_JAVA_WEEK              4053
#define STSCODE_STM_PERIODIC_SVC_JAVA_MONTH             4054
#define STSCODE_STM_SCHEDULE_SVC_JAVA                   4055
            
#define STSCODE_STM_PERIODIC_SVC_VODS_MINUTE            4060
#define STSCODE_STM_PERIODIC_SVC_VODS_HOUR              4061
#define STSCODE_STM_PERIODIC_SVC_VODS_DAY               4062
#define STSCODE_STM_PERIODIC_SVC_VODS_WEEK              4063
#define STSCODE_STM_PERIODIC_SVC_VODS_MONTH             4064
#define STSCODE_STM_SCHEDULE_SVC_VODS                   4065

#define STSCODE_STM_PERIODIC_SVC_WIPI_MINUTE            4070
#define STSCODE_STM_PERIODIC_SVC_WIPI_HOUR              4071
#define STSCODE_STM_PERIODIC_SVC_WIPI_DAY               4072
#define STSCODE_STM_PERIODIC_SVC_WIPI_WEEK              4073
#define STSCODE_STM_PERIODIC_SVC_WIPI_MONTH             4074
#define STSCODE_STM_SCHEDULE_SVC_WIPI                   4075

#define STSCODE_STM_PERIODIC_CDR2_MINUTE                4080
#define STSCODE_STM_PERIODIC_CDR2_HOUR                  4081
#define STSCODE_STM_PERIODIC_CDR2_DAY                   4082
#define STSCODE_STM_PERIODIC_CDR2_WEEK                  4083
#define STSCODE_STM_PERIODIC_CDR2_MONTH                 4084
#define STSCODE_STM_SCHEDULE_CDR2                       4085

#define STSCODE_STM_PERIODIC_FAIL_UDR_MINUTE            4090
#define STSCODE_STM_PERIODIC_FAIL_UDR_HOUR              4091
#define STSCODE_STM_PERIODIC_FAIL_UDR_DAY               4092
#define STSCODE_STM_PERIODIC_FAIL_UDR_WEEK              4093
#define STSCODE_STM_PERIODIC_FAIL_UDR_MONTH             4094
#define STSCODE_STM_SCHEDULE_FAIL_UDR                   4095
*/

#endif
